version: "3"

services:
  runner:
    build:
      dockerfile: Dockerfile
      context: .
    # Docker outside of docker needs root user permission
    user: root
    command: "./init.sh"
    # command: "/bin/bash"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./runner_config_cache:/actions-runner/config_cache
      - ./init.sh:/actions-runner/init.sh
    restart: unless-stopped
    init: true
    environment:
      GITHUB_ORG_TOKEN: $GITHUB_ORG_TOKEN
      GITHUB_ORG: $GITHUB_ORG
      RUNNER_URL: $RUNNER_URL
      RUNNER_LABELS: "container,cimg"
      NAME_PREFIX: ""
    # privileged: true
