version: "3"
services:
  runner:
    build:
      dockerfile: Dockerfile
      context: .
    # command: "./init.sh"
    command: "/bin/bash"
    volumes:
      - ./cimg-runner/config_cache:/actions-runner/config_cache
      - ./init.sh:/actions-runner/init.sh
    restart: unless-stopped
    init: true
    environment:
      GITHUB_ORG_TOKEN: $GITHUB_ORG_TOKEN
      GITHUB_ORG: $GITHUB_ORG
      RUNNER_URL: $RUNNER_URL
      RUNNER_NAME: "cimg-runner"
      RUNNER_LABELS: "container,cimg"
