version: '3'

services:
  worker:
    image: myoung34/github-runner:latest
    restart: unless-stopped
    environment:
      # REPO_URL: https://github.com/example/repo
      RUNNER_WORKDIR: /tmp/runner/work
      RUNNER_GROUP: Default
      ORG_NAME: $GITHUB_ORG
      RUNNER_SCOPE: 'org'
      LABELS: container
      # RUNNER_TOKEN: someGithubTokenHere
      ACCESS_TOKEN: $GITHUB_ORG_TOKEN
      # RUNNER_NAME: docker-github-actions-runner
      RUNNER_NAME_PREFIX: 'docker-github-actions'
    # security_opt:
    #   # needed on SELinux systems to allow docker container to manage other docker containers
    #   - label:disable
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      # - '/tmp/runner:/tmp/runner'
      # note: a quirk of docker-in-docker is that this path
      # needs to be the same path on host and inside the container,
      # docker mgmt cmds run outside of docker but expect the paths from within